import type { Metadata } from "next"
import { Inter, Poppins, Montserrat_Alternates } from "next/font/google"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import Header from "@/components/Header"
import { ThemeProvider } from "@/components/ThemeProvider"
import { Toast } from "@/components/ui/toast"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })
const poppins = Poppins({ weight: "500", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "File Sphere",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} ${poppins.className} `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
